stages:
  dataset:
    cmd: poetry run python -m mlops.dataset
    deps:
      - data/raw/seoul_bike_sharing.csv
      - mlops/dataset.py
    outs:
      - data/interim/seoul_bike_sharing_cleaned.csv

  features:
    cmd: poetry run python -m mlops.features
    deps:
      - data/interim/seoul_bike_sharing_cleaned.csv
      - mlops/features.py
    outs:
      - data/processed/seoul_bike_sharing_featured.csv

  train:
    cmd: poetry run python -m mlops.modeling.train
    deps:
      - data/processed/seoul_bike_sharing_featured.csv
      - mlops/modeling/train.py
    outs:
      - models/best_model.pkl

  predict:
    cmd: poetry run python -m mlops.modeling.predict
    deps:
      - data/processed/seoul_bike_sharing_featured.csv
      - models/best_model.pkl
      - mlops/modeling/predict.py
    outs:
      - data/processed/test_predictions.csv

  plots:
    cmd: poetry run python -m mlops.plots
    deps:
      - data/processed/seoul_bike_sharing_featured.csv
      - models/best_model.pkl
      - data/processed/test_predictions.csv
      - mlops/plots.py
    outs:
      - reports/figures/correlation_heatmap.png
      - reports/figures/demand_by_hour.png
      - reports/figures/target_distribution.png