stages:
  dataset:
    cmd: poetry run python -m mlops.dataset
    deps:
      - data/raw/seoul_bike_sharing.csv
      - mlops/dataset.py
    outs:
      - data/interim/seoul_bike_sharing_cleaned.csv

  features:
    cmd: poetry run python -m mlops.features
    deps:
      - data/interim/seoul_bike_sharing_cleaned.csv
      - mlops/features.py
    outs:
      - data/processed/seoul_bike_sharing_featured.csv

  train:
    # This stage now runs all experiments defined in experiments.yaml
    cmd: poetry run python run_experiments.py
    deps:
      - data/processed/seoul_bike_sharing_featured.csv
      - mlops/modeling/train.py
      - run_experiments.py
      - experiments.yaml
    # This stage no longer produces a local file, it only logs to MLflow.
    # Therefore, it has no 'outs'.

  promote_model:
    # This script queries MLflow and saves the best model.
    cmd: poetry run python run_promote_model.py
    deps:
      - run_promote_model.py
    # DVC now tracks the model that this script produces.
    outs:
      - models/best_model.pkl

  predict:
    cmd: poetry run python -m mlops.modeling.predict
    deps:
      - models/best_model.pkl
      - mlops/modeling/predict.py
    outs:
      - data/processed/test_predictions.csv

  plots:
    cmd: poetry run python -m mlops.plots
    deps:
      - data/processed/seoul_bike_sharing_featured.csv
      - models/best_model.pkl
      - data/processed/test_predictions.csv
      - mlops/plots.py
    outs:
      - reports/figures/correlation_heatmap.png
      - reports/figures/demand_by_hour.png
      - reports/figures/target_distribution.png